[package]
authors = ["Walfie <walfington@gmail.com>"]
name = "petronel-gbfrf"
version = "0.1.0"
build = "build.rs"

[build-dependencies.prost-build]
git = "https://github.com/danburkert/prost"
rev = "81064115e77f12185df6ea2b303c85727cd4eebb"

[dependencies.prost]
git = "https://github.com/danburkert/prost"
rev = "81064115e77f12185df6ea2b303c85727cd4eebb"

[dependencies.prost-derive]
git = "https://github.com/danburkert/prost"
rev = "81064115e77f12185df6ea2b303c85727cd4eebb"

[dependencies.prost-types]
git = "https://github.com/danburkert/prost"
rev = "81064115e77f12185df6ea2b303c85727cd4eebb"

[dependencies]
bytes = "0.4.5"
