[package]
authors = ["Walfie <walfington@gmail.com>"]
build = "build.rs"
name = "petronel-gbfrf"
version = "0.1.0"

[build-dependencies]
prost-build = "0.2.0"

[dependencies]
byteorder = "1.1.0"
bytes = "0.4.5"
futures = "0.1.15"
prost = "0.2.0"
prost-derive = "0.2.0"
prost-types = "0.2.0"
tk-bufstream = "0.3.0"
tk-http = "0.3.1"
tk-listen = "0.1.0"
tokio-core = "0.1.9"
